version: '3'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootmysql
      MYSQL_DATABASE: qlqa
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  spring-boot-app:
    container_name: qlqa-springboot
    build:
     context: ./
     dockerfile: Dockerfile
    ports:
      - "8080:8080" 
    depends_on:
      - mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: rootmysql
    ports:
      - "8081:80"
    depends_on:
      - mysql

volumes:
  mysql-data:
